# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: <ES_HOST>

# The elasticsearch port
es_port: <ES_PORT>

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 5

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
use_ssl: <ES_SSL>

# Verify TLS certificates
verify_certs: <ES_VERIFY_CERT>

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: <ES_USERNAME>
es_password: <ES_PASSWORD>

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

smtp_host: <SMTP_HOST>
smtp_port: <SMTP_PORT>
smtp_auth_file: /opt/elastalert/mail_auth.yml
from_addr: <FROM_ADDRESS>
